-
  name: Add name server entry if not already entered
  hosts: localhost
  vars:
    ip: 10.0.250.10
  tasks:
    - shell: cat /etc/resolv.conf
      register: command_output

    -
      shell: echo "nameserver {{ip}}" >> /etc/resolv.conf
      when: command_output.stdout.find("{{ip}}") == -1